server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: V5tQFi1M2BRnuFn0JPLKxVq15egthkRZ
            client-secret: u_8IGWdC0ertjzhPj9GeikRfaKI9KVH0moW98ESgpqeoMVGY7B6_ElAquafvMvGF
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://openuni.us.auth0.com/
